### ISSUE TITLE
Fix width

### ISSUE THREAD

**Issue by viki53** [SansPseudoFix/Old_menu#4]
Hi, on large screens the menu can get larger than needed.

I edited my CSS files as follow to get the proper width and enlarge the icons that were tiny:

```css
@media screen and (min-width: 1100px){

#expanddiv {background-color: #1d2d44;}
#app-navigation + #app-content #controls{width: 74.2% !important;left: 24.3% !important;}
#content {margin-top: 0px;}
#content-wrapper {padding-left: 5.63em !important;width: 100% !important;}
#navigation{
    background-color: #1d2d44;
    visibility:visible;
    display: block !important;
    position:fixed !important;
    bottom:0px;
    width: 5.63em !important;
    top:45px;
    max-height: 100% !important;
    margin-top:0px !important;
    -moz-user-select: none;
    -moz-box-sizing: border-box;
    box-shadow: 0px 0px 0px transparent;
    border-radius: 0px;
}
#navigation li{display: block; margin: .5em 0; }
#navigation a{display: block; width: auto; height: 100%; padding: 0 .25em; margin: 0;}
#navigation #apps { margin-left:0; margin-top: 10px; }
#navigation #apps ul{text-align: center;}
#navigation .app-icon{ height: 1.5em;width: 1.5em; }
#navigation a span{ display: block; width: auto; font-size: 11px; }


/***********************************************************
*
*       Core & default apps
*
************************************************************/    

/* oc 7 compatibility */
#leftcontent{width: 21% !important;}
#rightcontent{width: 78% !important;}
/* /oc 7 */
  
#app-navigation{width: 19.5% !important;}
#bookmark_settings {width:19.5% !important;}
.bookmarks_list, #firstrun {left:27% !important;}
#navigation .wrapper {margin: auto;}
#header .icon-caret {display:none;}

table.multiselect thead{width: 76% !important; left: 24.3% !important; margin: 0px !important; }
#slideshow{z-index: 5000 !important;}

/***********************************************************
*
*       3rd Party Apps
*
************************************************************/

/* owncloud-markdown (https://github.com/icewind1991/owncloud-markdown) */
#md_preview {padding-left: 60px;}

}
```
